export * from './articlesCR.service';
import { ArticlesCRService } from './articlesCR.service';
export * from './articlesPP.service';
import { ArticlesPPService } from './articlesPP.service';
export * from './checklists.service';
import { ChecklistsService } from './checklists.service';
export * from './csinquiries.service';
import { CsinquiriesService } from './csinquiries.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './messageConversations.service';
import { MessageConversationsService } from './messageConversations.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './productionPlannings.service';
import { ProductionPlanningsService } from './productionPlannings.service';
export * from './stepChecklists.service';
import { StepChecklistsService } from './stepChecklists.service';
export * from './steps.service';
import { StepsService } from './steps.service';
export * from './tlinquiries.service';
import { TlinquiriesService } from './tlinquiries.service';
export const APIS = [ArticlesCRService, ArticlesPPService, ChecklistsService, CsinquiriesService, FilesService, MessageConversationsService, MessagesService, OrdersService, ProductionPlanningsService, StepChecklistsService, StepsService, TlinquiriesService];
