/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddOrderDto { 
    customerName: string;
    additionalInformation?: string | null;
    createdBy: string;
    amount: number;
    checklistId?: number | null;
    csId?: number | null;
    tlId?: number | null;
    ppId?: number | null;
}

