/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Csinquiry } from './csinquiry';


export interface Article { 
    id?: number;
    articleNumber?: number;
    isDirectLine?: boolean;
    minHeigthRequired?: number;
    desiredDeliveryDate?: string | null;
    deliveryDate?: string | null;
    shortText?: string | null;
    factory?: string | null;
    nozzle?: string | null;
    productionOrder?: string | null;
    plannedOrder?: string | null;
    inquiryForFixedOrder?: boolean;
    inquiryForQuotation?: boolean;
    additionalInformation?: string | null;
    isFastLine?: boolean;
    pallets?: number;
    csinquiryId?: number;
    plant?: string | null;
    csinquiry?: Csinquiry;
}

