/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EditCsinquiryDto { 
    id: number;
    container: string;
    fastLine: string;
    directLine: string;
    articleNumber: string;
    palletamount: number;
    customer: string;
    abnumber: number;
    bruttoWeightInKg: number;
    incoterm: string;
    containersizeA: number;
    containersizeB: number;
    containersizeHc: number;
    freeDetention: boolean;
    thctb: boolean;
    readyToLoad: string;
    loadingPlattform: string;
}

