/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EditPpPpArticleDto { 
    id: number;
    deliveryDate: number;
    nozzle?: string | null;
    shortText?: string | null;
    factory?: string | null;
    productionOrder?: string | null;
    plannedOrder?: string | null;
    plant?: string | null;
}

