/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageConversation } from './messageConversation';


export interface Message { 
    id?: number;
    content?: string | null;
    attachmentId?: number | null;
    from?: string | null;
    dateTime?: string;
    attachment?: any;
    readonly messageConversations?: Array<MessageConversation> | null;
}

