/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDto { 
    id: number;
    status: string;
    customerName: string;
    createdBy: string;
    approvedByCrCs: boolean;
    approvedByPpCs: boolean;
    approvedByPpPp: boolean;
    approvedByCrTl: boolean;
    approvedByCsTime: string;
    approvedByTlTime: string;
    approvedByPpCsTime: string;
    approvedByPpPpTime: string;
    amount: number;
    additionalInformation: string;
    lastUpdated: string;
    checklistId: number;
    sped: string;
    country: string;
    readyToLoad: string;
    abNumber: number;
    csid: number;
    tlid: number;
}

