/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductionPlanningDto { 
    id: number;
    approvedByPpCs: boolean;
    approvedByPpPp: boolean;
    approvedByPpCsTime: string;
    approvedByPpPpTime: string;
    recievingCountry: string;
    customerPriority: string;
}

