/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { ArticlePP } from './articlePP';


export interface ProductionPlanning { 
    id?: number;
    approvedByPpCs?: boolean;
    approvedByPpPp?: boolean;
    recievingCountry?: string | null;
    customerPriority?: string;
    approvedByPpCsTime?: string | null;
    approvedByPpPpTime?: string | null;
    readonly articles?: Array<ArticlePP> | null;
    readonly orders?: Array<Order> | null;
}

