/**
 * Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TlinquiryDto { 
    id: number;
    sped: string;
    acceptingPort: string;
    invoiceOn: string;
    retrieveDate: string;
    retrieveLocation: string;
    scGeneral: number;
    scMain: number;
    scTrail: number;
    portOfDeparture: string;
    ets: string;
    eta: string;
    boat: string;
    approvedByCrTl: boolean;
    approvedByCrTlTime: string;
}

